NAME = philo

INC = philo.h

SRC = philo.c error_function.c parse_input.c data_init.c

CFLAG = cc -Wall -Wextra -Werror -I

all: $(NAME)

$(NAME) :
		$(CFLAG) $(INC) $(SRC) -o $(NAME)

fclean :
		rm -rf $(NAME)

re : fclean $(NAME)